FROM node:latest@sha256:6a404b2b928f9b2d3cc624388be3da12d848b8268cbd0440394bc64fc80bdb99
WORKDIR /workspace
ENV NODE_OPTIONS="--dns-result-order=ipv4first"
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq -y update \
    && apt-get -qq install -y --no-install-recommends zip \
    && npm install -G npm-check-updates
# CMD ["/workspace/node_modules/.bin/ncu", "-u"]
CMD ["npm", "run", "build"]
