FROM node:latest@sha256:ab9ada02d0430fa5965401beec32042d64bddbb3ff3aaf2b2263abddf77eb18a
WORKDIR /workspace
ENV NODE_OPTIONS="--dns-result-order=ipv4first"
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get -qq -y update \
    && apt-get -qq install -y --no-install-recommends zip \
    && npm install -G npm-check-updates
# CMD ["/workspace/node_modules/.bin/ncu", "-u"]
CMD ["npm", "run", "build"]
